import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Navigation } from './components/navigation';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  header,
}: Readonly<{
  children: React.ReactNode;
  header: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='min-h-screen grid grid-cols-3 gap-4'>
          <div className='col-span-3'>{header}</div>
          <div>
            <Navigation />
          </div>
          <div className='col-span-2'>{children}</div>
        </div>
      </body>
    </html>
  );
}
